[
    {
        "key": "dbln",
        "value": "%7B%2261586785887057%22%3A%22iaQzeoYo%22%7D",
        "domain": "facebook.com",
        "path": "/login/device-based/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.690Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "datr",
        "value": "JhijabMErphbbmiWGqAFnv11",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "sb",
        "value": "Jhijad99kEBmLjvsyJLbMzT1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "m_pixel_ratio",
        "value": "2.768749952316284",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "wd",
        "value": "391x867",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "c_user",
        "value": "61586785887057",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "xs",
        "value": "34%3AZmT7hkL9Ojf66g%3A2%3A1772296275%3A-1%3A-1",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "fr",
        "value": "0CLDebb3iAq98V4jp.AWdZ5URiH3kQ8qZq2XVFShCCrbG9nEOQwbPzkTUbyDNDdG7lRGY.Bpoxgm..AAA.0.0.BpoxhY.AWew7AxLhPtTUzis7HDpojClXw4",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "locale",
        "value": "en_US",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "pas",
        "value": "61586785887057%3AgSsBYx5XMW",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "wl_cbv",
        "value": "v2%3Bclient_version%3A3100%3Btimestamp%3A1772296280",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "fbl_st",
        "value": "101721630%3BT%3A29538271",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    },
    {
        "key": "vpd",
        "value": "v1%3B750x391x2.768749952316284",
        "domain": "facebook.com",
        "path": "/",
        "hostOnly": false,
        "creation": "2026-02-28T16:40:32.691Z",
        "lastAccessed": "2026-02-28T16:40:32.691Z"
    }
]
